easy_admin:
    entities:
        Property:
            class: App\Entity\Property
            role_prefix: ROLE_PROPERTIES_MANAGER
            label: 'Propriétés'
            form:
                fields:
                    - { property: 'ref', label: 'Référence' }
                    - { property: 'title', label: 'Nom du bien' }
                    - { property: 'description', label: 'Description', type: 'textarea'}
                    - { property: 'pictureFile', label: 'Photo', type: 'vich_image' }
                    - { property: 'picture_kitchen_file', label: 'Photo cuisine', type: 'vich_image' }
                    - { property: 'picture_bedroom_file', label: 'Photo chambre', type: 'vich_image' }
                    - { property: 'picture_bathroom_file', label: 'Photo salle de bain', type: 'vich_image' }
                    - { property: 'picture_livingroom_file', label: 'Photo salon', type: 'vich_image' }
                    - { property: 'price', label: 'Prix', type: 'money', type_options: { currency: 'EUR' }}
                    - { property: 'surface', label: 'Surface' }
                    - { property: 'adress', label: 'Adresse' }
                    - { property: 'postal_code', label: 'Code postal' }
                    - { property: 'city', label: 'Ville', type: 'text'}
                    - { property: 'rooms', label: 'Nombre de pièces' }
                    - { property: 'bedrooms', label: 'Nombre de chambres' }
                    - { property: 'type', label: 'Type'}
                    - { property: 'garage', label: 'Garage' }
                    - { property: 'parking', label: 'Parking' }
                    - { property: 'balcony', label: 'Balcon' }
                    - { property: 'garden', label: 'Jardin' }
                    - { property: 'floor', label: 'Étage' }
                    - { property: 'rental', label: 'Location' }
                    - { property: 'sale', label: 'Vente' }
                    - { property: 'furnished', label: 'Meublé' }
                    - { property: 'caretaker', label: 'Gardien' }
                    - { property: 'handicap_access', label: 'Accès handicapé' }
                    - { property: 'heater', label: 'Chauffage' }
#                    - { property: 'create_at', label: 'Date de création', type: ''}
            list:
                fields: [{property: 'ref', label: 'Référence', type: 'text'}, { property: 'title', label: 'Nom du bien'}, { property: 'picture', label: 'Photos', type: 'image', base_path: '/images/properties' }, { property: 'price', label: 'Prix', type: 'text' }, { property: 'adress', label: 'Adresse' }, { property: 'postal_code', label: 'Code postal', type: 'text'}, { property: 'city', label: 'Ville' }]


        User:
            class: App\Entity\User
#            role_prefix: ROLE_ADMIN
            label: 'Utilisateurs'
            form:
                fields:
                    - { property: 'username', label: "Nom d'utilisateur" }
                    # - { property: 'password', label: 'Mot de passe', type: password  }
                    - { property: 'firstname', label: 'Prénom'}
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'phone', label: 'Téléphone' }
                    - { property: 'is_verified', label: 'Email vérifié', type: 'checkbox' }
                    - { property: 'roles', label: 'Rôles', type: 'choice',  type_options: { choices: [Utilisateur: 'ROLE_USER', Administrateur: 'ROLE_ADMIN', Gestionnaire: 'ROLE_PROPERTIES_MANAGER'], expanded: true, multiple: true} }
            list:
                item_permission: 'ROLE_ADMIN'
                title: "Liste des utilisateurs"
                fields: ['id',{ property: 'rolesPretty', label: 'Administrateur' }, { property: 'username', label: "Nom d'utilisateur"}, { property: 'firstname', label: 'Prénom'}, { property: 'lastname', label: 'Nom'}, { property: 'phone', label: 'Téléphone', type: tel }, { property: 'email', label: 'Email', type: email }, {  property: 'is_verified', label: 'Email vérifié', type: toggle}]

    design:
        menu:
            - {entity: 'Property', icon: 'home', permission: ROLE_PROPERTIES_MANAGER}
            - {entity: 'User', icon: 'user', permission: ROLE_ADMIN}

